# --- Font Setup ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      none
bold_italic_font none

# --- Font Size ---
# 11.0 to 12.0 is the sweet spot on standard 1080p/1440p screens.
# If you run scaling (e.g. 1.25x on Wayland), 11.0 works best.
font_size 14.0

# Disable font variations/features if you want zero dynamic styled text
disable_ligatures never
confirm_os_window_close 0
background_opacity 0.60
# --- Tmux Integration ---
# Launches tmux, attaches to an existing session, or creates a new one
shell tmux new-session -A -s main
